spring.application.name=ubicacion

#spring.datasource.url=jdbc:mysql://localhost:3306/ubicacion?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.url=jdbc:mysql://localhost:3306/ubicacion
spring.datasource.username=root
spring.datasource.password=2001pxndxjose


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false