spring.application.name=ubicacion

#spring.datasource.url=jdbc:mysql://localhost:3306/ubicacion?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

server.port=8082
server.address=0.0.0.0
eureka.client.serviceUrl.defaultZone=http://26.227.33.49:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=26.111.237.70
eureka.instance.hostname=26.111.237.70
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}



bot.security.username=bot_consultas@ayuntamiento.com
bot.security.password=mO5gg7XWbO4rhU2Zu7XAjWEEAV0VT5!
jwt.rsa.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtb374qvIdtKg8/mN4NAHzN5gVo2fq5t48HIbhPPA1qqgrMzmx4yJIPQZgKNGA9+J59zyqpjBnHOdY+k7qsrqNwIbICMs7FmOSkfmVorbNIWP+CeOQG1s2CY9YNahH5b/HOIfK9piPSx+Znpf/9KhPoN0/k9mvd4mL/zntIOPu+RaR5JST/Sl7w4tUgAWB7eklLlXXeSXoXYWbOfSNK2b50KXkkCozma4EqzMwhe8K7AAfp3CBFQNhV6fjtPjF/Z7bgM/V8DqA8QnJ4nZRWBwEbG6Vc1KvYYRAl9X6IIqBHgMZD8hCzSpMXSemVWPnmPf499896RW/DQ3lGnBcV4X8QIDAQAB